# Student Alcohol Consumption

### Introduction:

This time you will download a dataset from the UCI.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/student-mat.csv).

### Step 3. Assign it to a variable called df.

In [2]:
url = "https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/student-mat.csv"
df = pd.read_csv(url)
display(df.head())

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

### Step 4. For the purpose of this exercise slice the dataframe from 'school' until the 'guardian' column

In [3]:
df_sliced = df.loc[:, 'school':'guardian']
display(df_sliced.head())

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother
4,GP,F,16,U,GT3,T,3,3,other,other,home,father

### Step 5. Create a lambda function that will capitalize strings.

In [4]:
capitalize_string = lambda x: x.capitalize()

### Step 6. Capitalize both Mjob and Fjob

In [5]:
df_sliced['Mjob'] = df_sliced['Mjob'].apply(capitalize_string)
df_sliced['Fjob'] = df_sliced['Fjob'].apply(capitalize_string)
display(df_sliced.head())

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,At_home,Teacher,course,mother
1,GP,F,17,U,GT3,T,1,1,At_home,Other,course,father
2,GP,F,15,U,LE3,T,1,1,At_home,Other,other,mother
3,GP,F,15,U,GT3,T,4,2,Health,Services,home,mother
4,GP,F,16,U,GT3,T,3,3,Other,Other,home,father

### Step 7. Print the last elements of the data set.

In [6]:
display(df_sliced.tail())

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
390,MS,M,20,U,LE3,A,2,2,Services,Services,course,other
391,MS,M,17,U,LE3,T,3,1,Services,Services,course,mother
392,MS,M,21,R,GT3,T,1,1,Other,Other,course,other
393,MS,M,18,R,LE3,T,3,2,Services,Other,course,mother
394,MS,M,19,U,LE3,T,1,1,Other,At_home,course,father

### Step 8. Did you notice the original dataframe is still lowercase? Why is that? Fix it and capitalize Mjob and Fjob.

In [7]:
df['Mjob'] = df['Mjob'].apply(capitalize_string)
df['Fjob'] = df['Fjob'].apply(capitalize_string)
display(df.head())

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,At_home,Teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,At_home,Other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,At_home,Other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,Health,Services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,Other,Other,...,4,3,2,1,2,5,4,6,10,10

### Step 9. Create a function called majority that returns a boolean value to a new column called legal_drinker (Consider majority as older than 17 years old)

In [8]:
def majority(age):
    return age > 17

df['legal_drinker'] = df['age'].apply(majority)
display(df.head())

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,legal_drinker
0,GP,F,18,U,GT3,A,4,4,At_home,Teacher,...,3,4,1,1,3,6,5,6,6,True
1,GP,F,17,U,GT3,T,1,1,At_home,Other,...,3,3,1,1,3,4,5,5,6,False
2,GP,F,15,U,LE3,T,1,1,At_home,Other,...,3,2,2,3,3,10,7,8,10,False
3,GP,F,15,U,GT3,T,4,2,Health,Services,...,2,2,1,1,5,2,15,14,15,False
4,GP,F,16,U,GT3,T,3,3,Other,Other,...,3,2,1,2,5,4,6,10,10,False

In [9]:
for col in df.columns:
    if df[col].dtype == 'int64' or df[col].dtype == 'float64':
        df[col] = df[col] * 10

display(df.head())

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,legal_drinker
0,GP,F,180,U,GT3,A,40,40,At_home,Teacher,...,30,40,10,10,30,60,50,60,60,True
1,GP,F,170,U,GT3,T,10,10,At_home,Other,...,30,30,10,10,30,40,50,50,60,False
2,GP,F,150,U,LE3,T,10,10,At_home,Other,...,30,20,20,30,30,100,70,80,100,False
3,GP,F,150,U,GT3,T,40,20,Health,Services,...,20,20,10,10,50,20,150,140,150,False
4,GP,F,160,U,GT3,T,30,30,Other,Other,...,30,20,10,20,50,40,60,100,100,False

### Step 10. Multiply every number of the dataset by 10.
##### I know this makes no sense, don't forget it is just an exercise

The previous cell already performed the multiplication of all numerical columns by 10. Displaying the head again to show the updated DataFrame.

In [10]:
display(df.head())

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,legal_drinker
0,GP,F,180,U,GT3,A,40,40,At_home,Teacher,...,30,40,10,10,30,60,50,60,60,True
1,GP,F,170,U,GT3,T,10,10,At_home,Other,...,30,30,10,10,30,40,50,50,60,False
2,GP,F,150,U,LE3,T,10,10,At_home,Other,...,30,20,20,30,30,100,70,80,100,False
3,GP,F,150,U,GT3,T,40,20,Health,Services,...,20,20,10,10,50,20,150,140,150,False
4,GP,F,160,U,GT3,T,30,30,Other,Other,...,30,20,10,20,50,40,60,100,100,False