# Pokemon

### Introduction:

This time you will create the data.



### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Create a data dictionary that looks like the DataFrame below

In [2]:
data = {
    'evolution': ['Ivysaur', 'Charmeleon', 'Wartortle', 'Metapod'],
    'hp': [45, 39, 44, 45],
    'name': ['Bulbasaur', 'Charmander', 'Squirtle', 'Caterpie'],
    'pokedex': ['yes', 'no', 'yes', 'no'],
    'type': ['grass', 'fire', 'water', 'bug']
}

### Step 3. Assign it to a variable called pokemon

In [4]:
pokemon = pd.DataFrame(data)
display(pokemon)

    evolution  hp        name pokedex   type
0     Ivysaur  45   Bulbasaur     yes  grass
1  Charmeleon  39  Charmander      no   fire
2   Wartortle  44    Squirtle     yes  water
3     Metapod  45    Caterpie      no    bug

### Step 4. Ops...it seems the DataFrame columns are in alphabetical order. Place  the order of the columns as name, type, hp, evolution, pokedex

In [5]:
pokemon = pokemon[['name', 'type', 'hp', 'evolution', 'pokedex']]
display(pokemon)

         name   type  hp   evolution pokedex
0   Bulbasaur  grass  45     Ivysaur     yes
1  Charmander   fire  39  Charmeleon      no
2    Squirtle  water  44   Wartortle     yes
3    Caterpie    bug  45     Metapod      no

### Step 5. Add another column called place, and insert what you have in mind.

In [6]:
pokemon['place'] = ['forest', 'volcano', 'ocean', 'forest']
display(pokemon)

         name   type  hp   evolution pokedex    place
0   Bulbasaur  grass  45     Ivysaur     yes   forest
1  Charmander   fire  39  Charmeleon      no  volcano
2    Squirtle  water  44   Wartortle     yes    ocean
3    Caterpie    bug  45     Metapod      no   forest

### Step 6. Present the type of each column

In [7]:
print(pokemon.dtypes)

name         object
type         object
hp            int64
evolution    object
pokedex      object
place        object
dtype: object

### BONUS: Create your own question and answer it.